### ISSUE TITLE
ResizableContent

### ISSUE THREAD

**Issue by dlaynes** [DanteCoder/react-resizableBox#8]
Good evening. Very cool plugin. I'm currently testing it.
Is there a way to add custom content to the component? I tried passing child props, but they won't show up. Thank you very much for your response.

**Comment by DanteCoder** [comment]
@dlaynes There is currently no way to pass custom components.
You can pass styles and class names to customize it.

What custom content are you thinking of using?

**Comment by dlaynes** [comment]
I see. I was thinking on adding text and images. What I'm going to do is to add a "shadow" component, with the same attributes, and play with the z-index of the elements.
I probably need to investigate how to do the rotation (that was easy, actually!).

**Comment by DanteCoder** [comment]
@dlaynes I see.

The way I made this box is to place it with "position: absolute". The images and text that you want to resize must also be positioned absolutely, with the same x and y coordinates that the resizable box gives you, but they are outside the box.
You can think of the box as an overlay that you can place over the elements you want to manipulate.

Let me know if you have any questions.
